language: node_js

addons:
 chrome:  75
 firefox: latest
 apt:
  packages:
   - dbus

before_install:
 - export $(dbus-launch)

matrix:
 include:
   - node_js: "stable"
     env: GULP_TASK="test-server"
   - node_js: "8"
     env: GULP_TASK="test-server"
   - node_js: "stable"
     env: GULP_TASK="test-client-travis"
   - node_js: "8"
     env: GULP_TASK="test-functional-testcafe-travis"
 fast_finish: true

notifications:
 email: false
