language: node_js

addons:
 chrome:  stable
 firefox: latest
 apt:
  packages:
   - dbus

before_install:
 # https://github.com/inikulin/publish-please/issues/66
 - |
   npm_version=$(npm -v);
   if [ ${npm_version:0:1} <= 3 ]; then
    npm install -g npm@latest;
   fi
 - export $(dbus-launch)

matrix:
 include:
   - node_js: "stable"
     env: GULP_TASK="test-server"
   - node_js: "6"
     env: GULP_TASK="test-server"
   - node_js: "stable"
     env: GULP_TASK="test-client-travis"
   - node_js: "stable"
     env: GULP_TASK="test-functional-testcafe-travis"
 fast_finish: true

notifications:
 email: false
